### ISSUE TITLE
Consider removing `_ScriptableObjects` from the config path

### ISSUE THREAD

**Issue by Weibye** [HenrysHouses/MultiSceneTools#4]
This of course comes from opinion and feel free to disregard this if you disagree :)

I am assuming that by having the config path be `Assets/_ScriptableObjects/MultiSceneTools/Config/` you prefer to bundle all scriptable objects within the `_ScriptableObjects` folder, regardless of where it belongs to? Or at least have all scriptable objects within subfolders of that folder?

In most of our projects at Breach, and in my personal projects, we are using a lot of different packages at the same time. More often than not we need to tell the various packages apart more than separating between scriptable objects and other types of content. 

It usually looks _somewhat_ like this:

```
Assets
| - ProjectName
     | - Materials
     | - Textures
     | - Prefabs
     | - Scripts
     | - ....
| - ExternalPackage1
    | - Scripts
    | - ScriptableObjects
    | - Textures
    | - Prefabs
| - ExternalPacakge2
    | - Scripts
    | - ScriptableObjects
    | - Config
| - ExternalPacakge3
```

So my suggestion would be to change the `configPath` to be `Assets/MultiSceneTools/Config/` in order to have a clearer project structure within this plugin whenever it is used in conjunction with other packages.

**Comment by HenrysHouses** [comment]
I have actually been thinking about this as our current project has been growing in size and I am starting to notice that our project file structure could be improved. So I agree this would be better.

**Comment by Weibye** [comment]
I find myself more often using the file hierarchy to try to find files from a specific plugin, package, system.

When looking for specific _types_ of files, like ~~scriptable objects~~, textures, materials or scenes, I'm using Unity's asset filters.

**Comment by Weibye** [comment]
But it looks like there's no filter for a ScriptableObject, at least not in `2021.3.x`. I could have sworn I have used it 😅 

![image](https://user-images.githubusercontent.com/13300393/229294911-83cc54dc-ac92-4610-83fd-910e0c5cf4e5.png)

**Comment by HenrysHouses** [comment]
Now the asset path should be updated and fixed a small issue with some undo's not registering on the config. 👍 But I assume there is a way to make your own types for filter searching because you can manually type in `t:ScriptableObject` in the search bar 👀

**Comment by HenrysHouses** [comment]
i got some help but apparently its not possible to add another item into that type list, but i managed to find a work around. 

```cs
// Get type
var editorAssembly = typeof(EditorWindow).Assembly;
System.Type projectBrowserType = editorAssembly.GetType("UnityEditor.ProjectBrowser");

// Get window instance
var WindowInstanceInfo = projectBrowserType.GetField("s_LastInteractedProjectBrowser");

// Call method
MethodInfo setSearchInfo = projectBrowserType.GetMethod("SetSearch", new [] {typeof(string)});
setSearchInfo.Invoke(WindowInstanceInfo.GetValue(projectBrowserType), new object[]{"t:ScriptableObject"});
```
